pipeline {
    
	agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    environment {
        NEXUS_VERSION = "nexus3"
        NEXUS_PROTOCOL = "http"
        NEXUS_USER = "admin"
        NEXUS_PASS = "admin123"
        SNAP_REPO = "vprofile-snapshot"
        RELEASE_REPO = "vprofile-release"
        CENTRAL_REPO = "vpro-maven-central"
        NEXUS_GRP_REPO = "vpro-maven-group"
        NEXUS_LOGIN = "nexuslogin"
        NEXUSIP = "172.31.11.17"
        NEXUSPORT= "8081"
        registeryCredntial = 'ecr:us-west-1:awscred'
        appRegistry = "349865279621.dkr.ecr.us-west-1.amazonaws.com/vprofileappimg"
        vprofileRegistry = "https://349865279621.dkr.ecr.us-west-1.amazonaws.com"
        cluster = 'vprofilestagingcluster'
        service = 'vproappstagesvc'

    }
    stages{
        stage('Build'){
            steps{
                sh "mvn -s settings.xml -DskipTests install"
            }
            post{
                success {
                    echo "Now Archiving"
                    archiveArtifacts artifacts: '**/*.war/'
                }
            }
        }
        stage('Test'){
            
            steps{
                sh 'mvn test'
            }
        }
        stage('Checkstyle Analysis'){
            steps {
                sh 'mvn checkstyle:checkstyle'
            }

        }
        stage('upload artifcat to nexus'){
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vproapp',
                        classifier: '',
                        file: 'target/vprofile-v2.war',
                        type: 'war']
                    ]
                )
            }

        }
        stage('build app image'){
            steps {
                script {
                    dockerImage = docker.build( appRegistry  , "./Docker-files/app/multistage/")
                }
            }
        }
        stage('upload app image'){
            steps {
                script {
                    docker.withRegistry(vprofileRegistry, registeryCredntial){
                        //dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage('Deploy to Ecs cluster'){
            steps {
                withAWS(credentials : 'awscred' , region: 'us-west-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
  post {
    success {
      slackSend channel : '#jenkinscicd', color: '#36a64f', message: "Deployment of myapp to production succeeded!"
    }
    failure {
      slackSend channel : '#jenkinscicd', color: '#ff0000', message: "Deployment of myapp to production failed!"
    }
  }
}
